# Generated by Django 3.1.3 on 2020-11-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image_id',
            new_name='picture_id',
        ),
    ]
