# Generated by Django 3.1.3 on 2020-11-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catcher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
